---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
spec:
  chart:
    spec:
      chart: mongodb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ext-bitnami
  interval: 100m
