---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s/01_flux/10_environments/charts/grafana/
      version: "0.0.1"
      sourceRef:
        kind: GitRepository
        name: grafana
      interval: 5m
  values:
    replicaCount: 1
