---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: grafana
  namespace: default
spec:
  interval: 10m0s
  url: https://github.com/essemenoff/cheatsheets.git
  ref:
    branch: master
