---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ext-bitnami
  namespace: default
spec:
  interval: 100m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
spec:
  interval: 5m
  chart:
      spec:
        chart: influxdb
        version: "5.4.11"
        sourceRef:
          kind: HelmRepository
          name: ext-bitnami
        interval: 10m
