---
kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: apple
  ports:
    - port: 8765
      targetPort: 5678
      protocol: TCP
  type: LoadBalancer
  externalIPs:
    - 192.168.60.10
---
apiVersion: v1
kind: Service
metadata:
  name: web2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: apple-service
  type: NodePort
