---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-myflux
  namespace: default
spec:
  chart:
    spec:
      chart: podinfo
      version: ">5.0.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ext-podinfo
  interval: 1m
  values:
    replicaCount: 3
